language: C++
sudo: required
dist: trusty
compiler: g++

install:
    - source ci/travis/install-linux.sh

before_script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt55/bin/qt55-env.sh

script:
    - mkdir build
    - cd build
    - cmake .. 
    - make
